name: CreateCache
on:
  schedule:    
    - cron:  '*/5 * * * *'
  push:
    branches:
      - master
jobs:        
  Main:      
    name: Create
    runs-on: ubuntu-latest   
    steps:
      - name : Other
        run: |
          apt-get install ffmpeg -y
          mkdir public
          echo "<center><h1>404 NOT FOUND</h1></center>" > public/404.html
          echo poster.orange-mikan.org > public/CNAME
      - name: DownLoad
        run: |
          cd public                                                            
          curl -L -o booth.jpeg "https://private.orange-mikan.org/ja/booth.jpeg"
          curl -L -o timeline.jpeg "https://private.orange-mikan.org/ja/timeline.jpeg"
          ffmpeg -framerate 1 -i booth.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 booth.mp4                    
          ffmpeg -framerate 1 -i timeline.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 timeline.mp4
      - name: gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               publish_dir: ./public
               force_orphan: false               
      - name: Invoke DeleteCache.yml
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: DeleteCache
          token: ${{ secrets.PERSONAL_TOKEN }}
