name: CreateCache
on:  
  schedule:    
    - cron:  '*/5 * * * *'
  workflow_dispatch:
  push:
    branches:
      - master
jobs:        
  Main:      
    name: Create
    runs-on: ubuntu-latest   
    steps:
      - name : Other
        run: |
          sudo apt-get install ffmpeg -y
          mkdir public
          echo "<center><h1>404 NOT FOUND</h1></center>" > public/404.html
          echo clone.orange-mikan.org > public/CNAME
      - name: DownLoad
        run: |
          cd public                                                            
          curl -L -o booth.jpeg "https://private.orange-mikan.org/ja/booth.jpeg"
          curl -L -o booth.jpeg "https://private.orange-mikan.org/ja/booth2.jpeg"
          curl -L -o timeline.jpeg "https://private.orange-mikan.org/ja/timeline.jpeg"
          curl -L -o timeline2.jpeg "https://private.orange-mikan.org/ja/timeline2.jpeg"
          curl -L -o timeline3.jpeg "https://private.orange-mikan.org/ja/timeline3.jpeg"
          curl -L -o vrchatworld.jpeg "https://private.orange-mikan.org/ja/vrchatworld.jpeg"
          curl -L -o vrchatworld2.jpeg "https://private.orange-mikan.org/ja/vrchatworld2.jpeg"
          curl -L -o vrchatworld3.jpeg "https://private.orange-mikan.org/ja/vrchatworld3.jpeg"
                              
          ffmpeg -framerate 1 -i booth.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 booth.mp4                    
          ffmpeg -framerate 1 -i booth2.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 booth2.mp4                   
          ffmpeg -framerate 1 -i timeline.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 timeline.mp4
          ffmpeg -framerate 1 -i timeline2.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 timeline2.mp4
          ffmpeg -framerate 1 -i timeline3.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 timeline3.mp4
          ffmpeg -framerate 1 -i vrchatworld.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 vrchatworld.mp4
          ffmpeg -framerate 1 -i vrchatworld2.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 vrchatworld2.mp4
          ffmpeg -framerate 1 -i vrchatworld3.jpeg -vframes 1 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -vcodec libx264 -pix_fmt yuv420p -crf 1 -r 60 vrchatworld3.mp4
                    
          rm *.jpeg
      - name: gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               publish_dir: ./public
               force_orphan: false               
      - name: Invoke DeleteCache.yml
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: DeleteCache
          token: ${{ secrets.PERSONAL_TOKEN }}
