name: DeleteCache
on: [ workflow_dispatch ]
jobs:        
  Main:      
    name: delete-cache
    runs-on: ubuntu-latest    
    steps:
      - name: apt-get
        run: |
          wget https://dot.net/v1/dotnet-install.sh
          sudo bash dotnet-install.sh
          sudo apt-get install -y git
      - name: git-clone
        run: |
          git clone https://github.com/aijkl/delete-cache.git                
      - name: dotnet-build
        run: |
          cd delete-cache/DeleteCache          
          sudo dotnet build DeleteCache.csproj --configuration Release          
      - name: run
        run: |                                        
          cd /home/runner/work/poster/poster/delete-cache/DeleteCache/bin/Release/netcoreapp3.0/                   
          sudo /home/runner/.dotnet/dotnet DeleteCache.dll ${{ secrets.APPSETTINGS }}    
                           
